[toolchain]
anchor_version = "1.0.0"
solana_version = "3.1.12"

[features]
resolution = true

[programs.localnet]
cat_system = "2MrZJsTvuSQ3HUtDozeGAm96eSrU1jCaVKjSSiu57Tzz"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
